export const producto = [
  {
    nombre: 'Producto 1',
    descripcion: 'Descripcion 1',
    precio: 10000,
    precioOferta: 5000,
    descuento: 50,
    stock: 15,
    usuarioId: 4,
    estadoProductoId: 1,
    categoriaProductoId: 1,
    tamannos: {
      connect: [{ id: 1 }],
    },
  },
  {
    nombre: 'Producto 2',
    descripcion: 'Descripcion 2',
    precio: 20000,
    precioOferta: 10000,
    descuento: 50,
    stock: 7,
    usuarioId: 5,
    estadoProductoId: 4,
    categoriaProductoId: 2,
    tamannos: {
      connect: [{ id: 1 }],
    },
  },
  {
    nombre: 'Producto 3',
    descripcion: 'Descripcion 3',
    precio: 30000,
    precioOferta: 21000,
    descuento: 30,
    stock: 12,
    usuarioId: 4,
    estadoProductoId: 3,
    categoriaProductoId: 3,
    tamannos: {
      connect: [{ id: 1 }],
    },
  },
  {
    nombre: 'Producto 4',
    descripcion: 'Descripcion 4',
    precio: 78000,
    precioOferta: 70200,
    descuento: 10,
    stock: 1,
    usuarioId: 5,
    estadoProductoId: 2,
    categoriaProductoId: 2,
    tamannos: {
      connect: { id: 1 },
    },
  },
];
